### ISSUE TITLE
ImportError: cannot import name 'cached_path'

### ISSUE THREAD

**Issue by SeekPoint** [huggingface/naacl_transfer_learning_tutorial#2]
ub16c9@ub16c9-gpu:/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/naacl_transfer_learning_tutorial$ python3.6 pretraining_train.py
Traceback (most recent call last):
  File "pretraining_train.py", line 21, in <module>
    from utils import get_and_tokenize_dataset, average_distributed_scalar, add_logging_and_checkpoint_saving, WEIGHTS_NAME
  File "/media/ub16c9/fcd84300-9270-4bbd-896a-5e04e79203b7/ub16_prj/naacl_transfer_learning_tutorial/utils.py", line 16, in <module>
    from pytorch_pretrained_bert import cached_path
ImportError: cannot import name 'cached_path'

**Comment by thomwolf** [comment]
Maybe you should install the latest version of `pytorch_pretrained_bert`?
`pip install pytorch_pretrained_bert --upgrade`
